### ISSUE TITLE
Can't import the module

### ISSUE THREAD

**Issue by zulkarnain-shah** [jeanetienne/rippl#10]
The import statement doesn't throw any compiler errors, but creating an outlet doesn't work. How to import it ?

**Comment by jeanetienne** [comment]
Hi Zulkarnain Shah,
Can you detail a bit more how you install the module? Through Carthage, CocoaPods, other? Can you detail the steps you went through?

**Comment by zulkarnain-shah** [comment]
At first I tried the normal procedure by adding the pod in podfile and then updating pods from terminal. That installed the pod just fine. When i created the view in my storyboard and set its class to Rippl, that time also it didn't complain. Then I brought an outlet of that view into my viewcontroller, that time I obviously had to import Rippl into my viewcontroller. That import statement was throwing error. Finally I found a solution to this by just copying the Rippl.swift file into my project and using it directly. That was the only way it worked

**Comment by jeanetienne** [comment]
Okay, yeah it should work if you just copy the sources, but it defeats the purpose of using dependency managers... 
I'll look into the CocoaPods issue soon and update this ticket with my findings.
Thanks for reporting it.

**Comment by zulkarnain-shah** [comment]
Great ! Ya, we should address the root cause of the problem rather than inventing specific work-arounds

**Comment by jeanetienne** [comment]
@zulkarnain-shah I finally had a chance to look into this issue. Sorry for the late response.
It was an error with the access control, the class was not declared as `public`... Duh!
Version `0.1.0` should fix this.
You may have to clean and rebuild, or even relaunch Xcode after updating your pods.

**Comment by zulkarnain-shah** [comment]
Great !
